[package]
name = "test_api"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = "0.6.0"
oas3 = "0.12.1"
reqwest = "0.12.9"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
